version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      rust-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - rust

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: npm
    directory: /website
    schedule:
      interval: weekly
    groups:
      website-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - website
