use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

/// Dashboard operation kind.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum DashboardOperationKind {
    /// HTTP request or response.
    Http,
    /// Observed event publication.
    Event,
    /// Observed job run.
    Job,
    /// Application lifecycle operation.
    Lifecycle,
    /// Official adapter operation.
    Adapter,
}

/// Dashboard operation status.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum DashboardOperationStatus {
    /// Operation succeeded.
    Success,
    /// Operation failed.
    Failure,
    /// Operation is in progress.
    Running,
}

/// Unified dashboard timeline operation.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct DashboardOperation {
    /// Stable operation identifier.
    pub id: String,
    /// Operation kind.
    pub kind: DashboardOperationKind,
    /// Stable operation name.
    pub name: String,
    /// Operation status.
    pub status: DashboardOperationStatus,
    /// Unix timestamp in milliseconds.
    pub timestamp_ms: i64,
    /// Duration in milliseconds, when known.
    pub duration_ms: Option<u64>,
    /// Request id, trace id, or run id when available.
    pub correlation_id: Option<String>,
    /// Stable metadata attributes.
    pub attributes: BTreeMap<String, String>,
    /// Optional redacted payload.
    pub payload: Option<serde_json::Value>,
}

/// Dashboard route snapshot record.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct DashboardRouteSnapshot {
    /// HTTP method.
    pub method: String,
    /// Full route path.
    pub path: String,
    /// Handler or summary label.
    pub summary: Option<String>,
    /// Guard type names.
    pub guards: Vec<String>,
    /// Pipe type names.
    pub pipes: Vec<String>,
    /// Whether validation is enabled.
    pub validates: bool,
}

/// Dashboard graph node kind.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum DashboardGraphNodeKind {
    /// Running application/runtime node.
    Runtime,
    /// Nidus module definition.
    Module,
    /// Provider declared by a module.
    Provider,
    /// Controller declared by a module.
    Controller,
    /// HTTP route generated by a controller.
    Route,
    /// Observed event publication.
    Event,
    /// Observed job run.
    Job,
    /// Observed adapter operation.
    Adapter,
}

/// Dashboard graph edge kind.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum DashboardGraphEdgeKind {
    /// Runtime owns the root/module graph.
    RuntimeModule,
    /// A module imports another module.
    ModuleImport,
    /// A module declares a provider.
    ModuleProvider,
    /// A module exports a provider.
    ModuleExport,
    /// A module declares a controller.
    ModuleController,
    /// A controller owns a route.
    ControllerRoute,
    /// Runtime activity is associated with a graph object.
    RuntimeActivity,
}

/// Stable dashboard graph node.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct DashboardGraphNode {
    /// Stable node identifier.
    pub id: String,
    /// Node kind.
    pub kind: DashboardGraphNodeKind,
    /// Human-readable label.
    pub label: String,
    /// Short display summary.
    pub summary: Option<String>,
    /// Optional runtime status.
    pub status: Option<String>,
    /// Small numeric facts for dense UI labels.
    pub counts: BTreeMap<String, usize>,
    /// Structured node metadata for inspection.
    pub metadata: BTreeMap<String, serde_json::Value>,
}

/// Stable dashboard graph edge.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct DashboardGraphEdge {
    /// Stable edge identifier.
    pub id: String,
    /// Edge kind.
    pub kind: DashboardGraphEdgeKind,
    /// Source node id.
    pub source: String,
    /// Target node id.
    pub target: String,
    /// Optional edge display label.
    pub label: Option<String>,
}

/// Optional graph layout group or lane.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct DashboardGraphGroup {
    /// Stable group identifier.
    pub id: String,
    /// Human-readable label.
    pub label: String,
    /// Node ids that belong to this group.
    pub nodes: Vec<String>,
}

/// Runtime graph response consumed by the embedded dashboard.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct DashboardGraphResponse {
    /// Service/runtime name.
    pub service_name: String,
    /// Unix timestamp in milliseconds.
    pub generated_at_ms: i64,
    /// Graph nodes.
    pub nodes: Vec<DashboardGraphNode>,
    /// Graph edges.
    pub edges: Vec<DashboardGraphEdge>,
    /// Optional graph groups/lanes.
    pub groups: Vec<DashboardGraphGroup>,
}

impl DashboardGraphResponse {
    /// Creates an empty graph response for a service.
    pub fn empty(service_name: impl Into<String>) -> Self {
        Self {
            service_name: service_name.into(),
            generated_at_ms: current_timestamp_ms(),
            nodes: Vec::new(),
            edges: Vec::new(),
            groups: Vec::new(),
        }
    }

    /// Refreshes the generation timestamp.
    pub fn refresh_timestamp(&mut self) {
        self.generated_at_ms = current_timestamp_ms();
    }
}

fn current_timestamp_ms() -> i64 {
    time::OffsetDateTime::now_utc().unix_timestamp_nanos() as i64 / 1_000_000
}
