//! OpenAPI document generation and serving support.

use axum::{Json, Router, response::Html, routing::get};
use nidus_http::error::RoutePathError;
use nidus_http::router::RouteMetadata;
use serde_json::{Value, json};
use utoipa::{PartialSchema, ToSchema};

/// Minimal OpenAPI document metadata builder.
#[derive(Clone, Debug)]
pub struct OpenApiDocument {
    title: String,
    version: String,
    routes: Vec<OpenApiRoute>,
    schemas: Vec<(String, Value)>,
}

impl OpenApiDocument {
    /// Creates an OpenAPI document.
    pub fn new(title: impl Into<String>, version: impl Into<String>) -> Self {
        Self {
            title: title.into(),
            version: version.into(),
            routes: Vec::new(),
            schemas: Vec::new(),
        }
    }

    /// Adds route metadata to the document.
    pub fn route(mut self, route: OpenApiRoute) -> Self {
        self.routes.push(route);
        self
    }

    /// Adds generated route metadata under a controller prefix.
    pub fn controller_routes(self, controller_prefix: &str, routes: &[RouteMetadata]) -> Self {
        self.try_controller_routes(controller_prefix, routes)
            .unwrap_or_else(|error| panic!("{error}"))
    }

    /// Tries to add generated route metadata under a controller prefix.
    pub fn try_controller_routes(
        mut self,
        controller_prefix: &str,
        routes: &[RouteMetadata],
    ) -> Result<Self, RoutePathError> {
        for route in routes {
            self = self.route(OpenApiRoute::try_from_route_metadata_at_path(
                route,
                route.try_full_path(controller_prefix)?,
            )?);
        }
        Ok(self)
    }

    /// Adds a DTO schema generated by `utoipa::ToSchema`.
    pub fn schema<T>(mut self) -> Self
    where
        T: ToSchema,
    {
        let mut schemas = vec![(T::name().to_string(), <T as PartialSchema>::schema())];
        T::schemas(&mut schemas);
        self.schemas
            .extend(schemas.into_iter().map(|(name, schema)| {
                (
                    name,
                    serde_json::to_value(schema)
                        .expect("utoipa schema serialization should not fail"),
                )
            }));
        self
    }

    /// Creates an OpenAPI document from generated route metadata.
    pub fn from_route_metadata(
        title: impl Into<String>,
        version: impl Into<String>,
        routes: &[RouteMetadata],
    ) -> Self {
        Self::try_from_route_metadata(title, version, routes)
            .unwrap_or_else(|error| panic!("{error}"))
    }

    /// Tries to create an OpenAPI document from generated route metadata.
    pub fn try_from_route_metadata(
        title: impl Into<String>,
        version: impl Into<String>,
        routes: &[RouteMetadata],
    ) -> Result<Self, RoutePathError> {
        let mut document = Self::new(title, version);
        for route in routes {
            document = document.route(OpenApiRoute::try_from_route_metadata(route)?);
        }
        Ok(document)
    }

    /// Creates an OpenAPI document from a controller prefix and generated route metadata.
    pub fn from_controller_routes(
        title: impl Into<String>,
        version: impl Into<String>,
        controller_prefix: &str,
        routes: &[RouteMetadata],
    ) -> Self {
        Self::try_from_controller_routes(title, version, controller_prefix, routes)
            .unwrap_or_else(|error| panic!("{error}"))
    }

    /// Tries to create an OpenAPI document from controller route metadata.
    pub fn try_from_controller_routes(
        title: impl Into<String>,
        version: impl Into<String>,
        controller_prefix: &str,
        routes: &[RouteMetadata],
    ) -> Result<Self, RoutePathError> {
        Self::new(title, version).try_controller_routes(controller_prefix, routes)
    }

    /// Renders the document as JSON.
    pub fn to_json_value(&self) -> Value {
        let mut paths = serde_json::Map::new();
        for route in &self.routes {
            let entry = paths
                .entry(route.path.clone())
                .or_insert_with(|| Value::Object(serde_json::Map::new()));
            if let Value::Object(methods) = entry {
                methods.insert(route.method.clone(), route.to_json_value());
            }
        }

        let mut document = json!({
            "openapi": "3.1.0",
            "info": {
                "title": self.title,
                "version": self.version,
            },
            "paths": paths,
        });

        if !self.schemas.is_empty() {
            let schemas = self
                .schemas
                .iter()
                .cloned()
                .collect::<serde_json::Map<_, _>>();
            document["components"] = json!({
                "schemas": schemas,
            });
        }

        document
    }

    /// Builds an Axum router serving OpenAPI JSON and Swagger UI docs.
    pub fn into_router(self) -> Router {
        let json = self.to_json_value();
        let docs = docs_html(&self.title, "/openapi.json");

        Router::new()
            .route(
                "/openapi.json",
                get(move || {
                    let json = json.clone();
                    async move { Json(json) }
                }),
            )
            .route(
                "/docs",
                get(move || {
                    let docs = docs.clone();
                    async move { Html(docs) }
                }),
            )
    }
}

/// OpenAPI route metadata.
#[derive(Clone, Debug)]
pub struct OpenApiRoute {
    method: String,
    path: String,
    path_parameters: Vec<String>,
    summary: Option<String>,
    tags: Vec<String>,
    request_schema: Option<String>,
    response_schema: Option<String>,
}

impl OpenApiRoute {
    /// Creates GET route metadata.
    pub fn get(path: impl Into<String>) -> Self {
        Self::try_get(path).unwrap_or_else(|error| panic!("{error}"))
    }

    /// Tries to create GET route metadata.
    pub fn try_get(path: impl Into<String>) -> Result<Self, RoutePathError> {
        Self::try_new("get", path)
    }

    /// Creates POST route metadata.
    pub fn post(path: impl Into<String>) -> Self {
        Self::try_post(path).unwrap_or_else(|error| panic!("{error}"))
    }

    /// Tries to create POST route metadata.
    pub fn try_post(path: impl Into<String>) -> Result<Self, RoutePathError> {
        Self::try_new("post", path)
    }

    /// Creates PUT route metadata.
    pub fn put(path: impl Into<String>) -> Self {
        Self::try_put(path).unwrap_or_else(|error| panic!("{error}"))
    }

    /// Tries to create PUT route metadata.
    pub fn try_put(path: impl Into<String>) -> Result<Self, RoutePathError> {
        Self::try_new("put", path)
    }

    /// Creates PATCH route metadata.
    pub fn patch(path: impl Into<String>) -> Self {
        Self::try_patch(path).unwrap_or_else(|error| panic!("{error}"))
    }

    /// Tries to create PATCH route metadata.
    pub fn try_patch(path: impl Into<String>) -> Result<Self, RoutePathError> {
        Self::try_new("patch", path)
    }

    /// Creates DELETE route metadata.
    pub fn delete(path: impl Into<String>) -> Self {
        Self::try_delete(path).unwrap_or_else(|error| panic!("{error}"))
    }

    /// Tries to create DELETE route metadata.
    pub fn try_delete(path: impl Into<String>) -> Result<Self, RoutePathError> {
        Self::try_new("delete", path)
    }

    /// Sets the route summary.
    pub fn summary(mut self, summary: impl Into<String>) -> Self {
        self.summary = Some(summary.into());
        self
    }

    /// Adds an OpenAPI tag to this operation.
    pub fn tag(mut self, tag: impl Into<String>) -> Self {
        self.tags.push(tag.into());
        self
    }

    /// Sets the JSON request body schema reference.
    pub fn request_schema<T>(self) -> Self
    where
        T: ToSchema,
    {
        self.request_schema_ref(T::name())
    }

    /// Sets the successful JSON response schema reference.
    pub fn response_schema<T>(self) -> Self
    where
        T: ToSchema,
    {
        self.response_schema_ref(T::name())
    }

    fn request_schema_ref(mut self, schema: impl Into<String>) -> Self {
        self.request_schema = Some(schema.into());
        self
    }

    fn response_schema_ref(mut self, schema: impl Into<String>) -> Self {
        self.response_schema = Some(schema.into());
        self
    }

    fn new(
        method: impl Into<String>,
        path: impl Into<String>,
        path_parameters: Vec<String>,
    ) -> Self {
        Self {
            method: method.into(),
            path: path.into(),
            path_parameters,
            summary: None,
            tags: Vec::new(),
            request_schema: None,
            response_schema: None,
        }
    }

    fn try_new(method: impl Into<String>, path: impl Into<String>) -> Result<Self, RoutePathError> {
        let path = path.into();
        let path = openapi_path(&path)?;
        let path_parameters = openapi_path_parameters(&path);
        Ok(Self::new(method, path, path_parameters))
    }

    fn try_from_route_metadata(metadata: &RouteMetadata) -> Result<Self, RoutePathError> {
        Self::try_from_route_metadata_at_path(metadata, metadata.path())
    }

    fn try_from_route_metadata_at_path(
        metadata: &RouteMetadata,
        path: impl AsRef<str>,
    ) -> Result<Self, RoutePathError> {
        let path = openapi_path(path.as_ref())?;
        let path_parameters = openapi_path_parameters(&path);
        let mut route = Self::new(
            metadata.method().to_ascii_lowercase(),
            path,
            path_parameters,
        );
        if let Some(summary) = metadata.summary() {
            route = route.summary(summary);
        }
        for tag in metadata.tags() {
            route = route.tag(*tag);
        }
        if let Some(schema) = metadata.request_schema() {
            route = route.request_schema_ref(schema);
        }
        if let Some(schema) = metadata.response_schema() {
            route = route.response_schema_ref(schema);
        }
        Ok(route)
    }

    fn to_json_value(&self) -> Value {
        let mut success_response = json!({
            "description": "Success"
        });
        if let Some(schema) = &self.response_schema {
            success_response["content"] = json!({
                "application/json": {
                    "schema": {
                        "$ref": format!("#/components/schemas/{schema}")
                    }
                }
            });
        }

        let mut operation = json!({
            "summary": self.summary,
            "responses": {
                "200": success_response
            }
        });

        if !self.tags.is_empty() {
            operation["tags"] = json!(self.tags);
        }
        if let Some(schema) = &self.request_schema {
            operation["requestBody"] = json!({
                "required": true,
                "content": {
                    "application/json": {
                        "schema": {
                            "$ref": format!("#/components/schemas/{schema}")
                        }
                    }
                }
            });
        }
        if !self.path_parameters.is_empty() {
            operation["parameters"] = json!(
                self.path_parameters
                    .iter()
                    .map(|name| {
                        json!({
                            "name": name,
                            "in": "path",
                            "required": true,
                            "schema": {
                                "type": "string"
                            }
                        })
                    })
                    .collect::<Vec<_>>()
            );
        }

        operation
    }
}

fn openapi_path(path: &str) -> Result<String, RoutePathError> {
    let mut segments = Vec::new();
    for segment in path.split('/') {
        if segment == ":" {
            return Err(RoutePathError::empty_parameter(path));
        }
        if let Some(name) = segment.strip_prefix(':') {
            segments.push(format!("{{{name}}}"));
        } else {
            segments.push(segment.to_owned());
        }
    }
    Ok(segments.join("/"))
}

fn openapi_path_parameters(path: &str) -> Vec<String> {
    path.split('/')
        .filter_map(|segment| {
            let name = segment.strip_prefix('{')?.strip_suffix('}')?;
            (!name.is_empty()).then(|| name.to_owned())
        })
        .collect()
}

fn docs_html(title: &str, spec_url: &str) -> String {
    let title = escape_html(title);
    let spec_url = escape_js_string(spec_url);
    format!(
        r##"<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title} Documentation</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swagger-ui-dist/swagger-ui.css">
</head>
<body>
  <div id="swagger-ui"></div>
  <script src="https://cdn.jsdelivr.net/npm/swagger-ui-dist/swagger-ui-bundle.js"></script>
  <script>
    window.ui = SwaggerUIBundle({{
      url: "{spec_url}",
      dom_id: "#swagger-ui"
    }});
  </script>
</body>
</html>"##
    )
}

fn escape_html(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

fn escape_js_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}
