//! OpenAPI document generation and serving support.

use axum::{Json, Router, routing::get};
use nidus_http::router::RouteMetadata;
use serde_json::{Value, json};
use utoipa::{PartialSchema, ToSchema};

/// Minimal OpenAPI document metadata builder.
#[derive(Clone, Debug)]
pub struct OpenApiDocument {
    title: String,
    version: String,
    routes: Vec<OpenApiRoute>,
    schemas: Vec<(String, Value)>,
}

impl OpenApiDocument {
    /// Creates an OpenAPI document.
    pub fn new(title: impl Into<String>, version: impl Into<String>) -> Self {
        Self {
            title: title.into(),
            version: version.into(),
            routes: Vec::new(),
            schemas: Vec::new(),
        }
    }

    /// Adds route metadata to the document.
    pub fn route(mut self, route: OpenApiRoute) -> Self {
        self.routes.push(route);
        self
    }

    /// Adds a DTO schema generated by `utoipa::ToSchema`.
    pub fn schema<T>(mut self) -> Self
    where
        T: ToSchema,
    {
        let mut schemas = vec![(T::name().to_string(), <T as PartialSchema>::schema())];
        T::schemas(&mut schemas);
        self.schemas
            .extend(schemas.into_iter().map(|(name, schema)| {
                (
                    name,
                    serde_json::to_value(schema)
                        .expect("utoipa schema serialization should not fail"),
                )
            }));
        self
    }

    /// Creates an OpenAPI document from generated route metadata.
    pub fn from_route_metadata(
        title: impl Into<String>,
        version: impl Into<String>,
        routes: &[RouteMetadata],
    ) -> Self {
        let mut document = Self::new(title, version);
        for route in routes {
            document = document.route(OpenApiRoute::from_route_metadata(route));
        }
        document
    }

    /// Renders the document as JSON.
    pub fn to_json_value(&self) -> Value {
        let mut paths = serde_json::Map::new();
        for route in &self.routes {
            let entry = paths
                .entry(route.path.clone())
                .or_insert_with(|| Value::Object(serde_json::Map::new()));
            if let Value::Object(methods) = entry {
                methods.insert(
                    route.method.clone(),
                    json!({
                        "summary": route.summary,
                        "responses": {
                            "200": {
                                "description": "Success"
                            }
                        }
                    }),
                );
            }
        }

        let mut document = json!({
            "openapi": "3.1.0",
            "info": {
                "title": self.title,
                "version": self.version,
            },
            "paths": paths,
        });

        if !self.schemas.is_empty() {
            let schemas = self
                .schemas
                .iter()
                .cloned()
                .collect::<serde_json::Map<_, _>>();
            document["components"] = json!({
                "schemas": schemas,
            });
        }

        document
    }

    /// Builds an Axum router serving OpenAPI JSON and a docs placeholder.
    pub fn into_router(self) -> Router {
        let json = self.to_json_value();
        let docs = format!("{} docs are available at /openapi.json", self.title);

        Router::new()
            .route(
                "/openapi.json",
                get(move || {
                    let json = json.clone();
                    async move { Json(json) }
                }),
            )
            .route("/docs", get(move || async move { docs }))
    }
}

/// OpenAPI route metadata.
#[derive(Clone, Debug)]
pub struct OpenApiRoute {
    method: String,
    path: String,
    summary: Option<String>,
}

impl OpenApiRoute {
    /// Creates GET route metadata.
    pub fn get(path: impl Into<String>) -> Self {
        Self::new("get", path)
    }

    /// Creates POST route metadata.
    pub fn post(path: impl Into<String>) -> Self {
        Self::new("post", path)
    }

    /// Sets the route summary.
    pub fn summary(mut self, summary: impl Into<String>) -> Self {
        self.summary = Some(summary.into());
        self
    }

    fn new(method: impl Into<String>, path: impl Into<String>) -> Self {
        Self {
            method: method.into(),
            path: path.into(),
            summary: None,
        }
    }

    fn from_route_metadata(metadata: &RouteMetadata) -> Self {
        let mut route = Self::new(
            metadata.method().to_ascii_lowercase(),
            openapi_path(metadata.path()),
        );
        if let Some(summary) = metadata.summary() {
            route = route.summary(summary);
        }
        route
    }
}

fn openapi_path(path: &str) -> String {
    path.split('/')
        .map(|segment| {
            if let Some(name) = segment.strip_prefix(':') {
                format!("{{{name}}}")
            } else {
                segment.to_owned()
            }
        })
        .collect::<Vec<_>>()
        .join("/")
}
