use std::{fs, path::Path};

use anyhow::{Context, Result, bail};

pub(crate) fn create_project(name: &str, root: &Path, nidus_path: Option<&Path>) -> Result<()> {
    let project = root.join(name);
    if project.exists() {
        bail!("project already exists: {}", project.display());
    }
    let src = project.join("src");
    fs::create_dir_all(&src).with_context(|| format!("creating {}", src.display()))?;
    let nidus_dependency = nidus_path
        .map(|path| format!("{{ path = {:?} }}", path.display().to_string()))
        .unwrap_or_else(|| "\"0.1\"".to_owned());
    write(
        &project.join("Cargo.toml"),
        &format!(
            r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2024"

[dependencies]
nidus = {nidus_dependency}
"#
        ),
    )?;
    write(
        &src.join("main.rs"),
        r#"use nidus::prelude::*;

#[nidus::main]
async fn main() -> std::result::Result<(), Box<dyn std::error::Error>> {
    let app = Controller::new("/")
        .route(RouteDefinition::get("/", || async { "hello from nidus" }))
        .into_router();

    Nidus::bootstrap::<AppModule>()?
        .with_router(app)
        .listen("127.0.0.1:3000")
        .await?;
    Ok(())
}

#[module]
struct AppModule;
"#,
    )?;
    write(
        &project.join("README.md"),
        &format!(
            r#"# {name}

Generated by `cargo nidus new`.

Run:

```bash
cargo run
```
"#
        ),
    )?;
    Ok(())
}

pub(crate) fn generate_artifact(kind: &str, name: &str, root: &Path) -> Result<()> {
    ensure_supported_artifact(kind)?;
    let module_name = to_snake_case(name);
    if module_name.is_empty() {
        bail!("artifact name must contain at least one ASCII letter or digit");
    }
    if !module_name.starts_with(|character: char| character.is_ascii_alphabetic()) {
        bail!("artifact name must start with an ASCII letter after normalization");
    }
    let directory_name = pluralize(kind);
    let directory = root.join("src").join(&directory_name);
    fs::create_dir_all(&directory).with_context(|| format!("creating {}", directory.display()))?;
    let path = directory.join(format!("{module_name}.rs"));
    if path.exists() {
        bail!("artifact already exists: {}", path.display());
    }
    write(&path, &artifact(kind, name, &module_name))?;
    update_module_index(&directory, &module_name)?;
    update_crate_root_module(root, &directory_name)
}

fn ensure_supported_artifact(kind: &str) -> Result<()> {
    if matches!(kind, "module" | "controller" | "service" | "repository") {
        Ok(())
    } else {
        bail!(
            "unsupported artifact kind `{kind}`. Expected one of: module, controller, service, repository"
        );
    }
}

fn write(path: &Path, contents: &str) -> Result<()> {
    fs::write(path, contents).with_context(|| format!("writing {}", path.display()))
}

fn update_module_index(directory: &Path, name: &str) -> Result<()> {
    let path = directory.join("mod.rs");
    let entry = format!("pub mod {name};");
    let mut entries = if path.exists() {
        fs::read_to_string(&path)
            .with_context(|| format!("reading {}", path.display()))?
            .lines()
            .map(str::trim)
            .filter(|line| !line.is_empty())
            .map(str::to_owned)
            .collect::<Vec<_>>()
    } else {
        Vec::new()
    };

    if !entries.iter().any(|existing| existing == &entry) {
        entries.push(entry);
        entries.sort();
    }

    let contents = if entries.is_empty() {
        String::new()
    } else {
        format!("{}\n", entries.join("\n"))
    };
    write(&path, &contents)
}

fn update_crate_root_module(root: &Path, module: &str) -> Result<()> {
    let src = root.join("src");
    let (path, visibility) = if src.join("lib.rs").exists() {
        (src.join("lib.rs"), "pub ")
    } else if src.join("main.rs").exists() {
        (src.join("main.rs"), "")
    } else {
        return Ok(());
    };
    let contents =
        fs::read_to_string(&path).with_context(|| format!("reading {}", path.display()))?;
    let private_entry = format!("mod {module};");
    let public_entry = format!("pub mod {module};");
    if contents
        .lines()
        .map(str::trim)
        .any(|line| line == private_entry || line == public_entry)
    {
        return Ok(());
    }

    let mut updated = contents;
    if !updated.ends_with('\n') {
        updated.push('\n');
    }
    updated.push_str(&format!("{visibility}mod {module};\n"));
    write(&path, &updated)
}

fn pluralize(kind: &str) -> String {
    match kind {
        "module" => "modules".to_owned(),
        "controller" => "controllers".to_owned(),
        "service" => "services".to_owned(),
        "repository" => "repositories".to_owned(),
        other => format!("{other}s"),
    }
}

fn artifact(kind: &str, name: &str, module_name: &str) -> String {
    let type_name = to_pascal_case(module_name);
    match kind {
        "module" => format!(
            r#"use nidus::prelude::*;

#[module]
#[allow(dead_code)]
pub struct {type_name}Module;
"#
        ),
        "controller" => format!(
            r#"use nidus::prelude::*;

#[controller("/{name}")]
#[allow(dead_code)]
pub struct {type_name}Controller;

#[routes]
#[allow(dead_code)]
impl {type_name}Controller {{
    #[get("/")]
    pub async fn index(&self) {{}}
}}
"#
        ),
        "service" => format!(
            r#"use nidus::prelude::*;

#[injectable]
#[allow(dead_code)]
pub struct {type_name}Service;
"#
        ),
        "repository" => format!(
            r#"use nidus::prelude::*;

#[injectable]
#[allow(dead_code)]
pub struct {type_name}Repository;
"#
        ),
        _ => unreachable!("artifact kind should be validated before rendering"),
    }
}

fn to_pascal_case(name: &str) -> String {
    name.split(['-', '_'])
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().chain(chars).collect::<String>(),
                None => String::new(),
            }
        })
        .collect()
}

fn to_snake_case(name: &str) -> String {
    let mut output = String::new();
    let mut previous_was_separator = true;

    for character in name.chars() {
        if character.is_ascii_alphanumeric() {
            if character.is_ascii_uppercase() && !previous_was_separator {
                output.push('_');
            }
            output.push(character.to_ascii_lowercase());
            previous_was_separator = false;
        } else if !previous_was_separator {
            output.push('_');
            previous_was_separator = true;
        }
    }

    if output.ends_with('_') {
        output.pop();
    }
    output
}
