use std::{
    fs,
    path::{Path, PathBuf},
};

use anyhow::{Context, Result, bail};
use clap::{Parser, Subcommand};

#[derive(Debug, Parser)]
#[command(name = "cargo-nidus", bin_name = "cargo nidus")]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Debug, Subcommand)]
enum Command {
    /// Create a new Nidus application.
    New {
        /// Project name.
        name: String,
        /// Directory where the project folder should be created.
        #[arg(long, default_value = ".")]
        path: PathBuf,
        /// Local path to the nidus facade crate, used by tests and unreleased development builds.
        #[arg(long, hide = true)]
        nidus_path: Option<PathBuf>,
    },
    /// Generate a framework artifact.
    Generate {
        /// Artifact kind: module, controller, service, or repository.
        kind: String,
        /// Artifact name.
        name: String,
        /// Project root.
        #[arg(long, default_value = ".")]
        path: PathBuf,
    },
    /// Print route metadata.
    Routes {
        /// Project root.
        #[arg(long, default_value = ".")]
        path: PathBuf,
    },
    /// Print dependency graph metadata.
    Graph {
        /// Project root.
        #[arg(long, default_value = ".")]
        path: PathBuf,
    },
    /// Print expanded generated code guidance.
    Expand,
    /// Check project structure.
    Check {
        /// Project root.
        #[arg(long, default_value = ".")]
        path: PathBuf,
    },
    /// Generate OpenAPI output.
    Openapi,
}

fn main() -> Result<()> {
    let args = std::env::args().collect::<Vec<_>>();
    let args = if args.get(1).is_some_and(|arg| arg == "nidus") {
        let mut stripped = Vec::with_capacity(args.len() - 1);
        stripped.push(args[0].clone());
        stripped.extend(args.iter().skip(2).cloned());
        stripped
    } else {
        args
    };
    let cli = Cli::parse_from(args);

    match cli.command {
        Command::New {
            name,
            path,
            nidus_path,
        } => create_project(&name, &path, nidus_path.as_deref()),
        Command::Generate { kind, name, path } => generate_artifact(&kind, &name, &path),
        Command::Routes { path } => inspect_routes(&path),
        Command::Graph { path } => inspect_graph(&path),
        Command::Expand => {
            println!("use cargo expand to inspect Nidus generated code");
            Ok(())
        }
        Command::Check { path } => check_project(&path),
        Command::Openapi => {
            println!("OpenAPI generation is available in projects using nidus-openapi");
            Ok(())
        }
    }
}

fn create_project(name: &str, root: &Path, nidus_path: Option<&Path>) -> Result<()> {
    let project = root.join(name);
    let src = project.join("src");
    fs::create_dir_all(&src).with_context(|| format!("creating {}", src.display()))?;
    let nidus_dependency = nidus_path
        .map(|path| format!("{{ path = {:?} }}", path.display().to_string()))
        .unwrap_or_else(|| "\"0.1\"".to_owned());
    write(
        &project.join("Cargo.toml"),
        &format!(
            r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
nidus = {nidus_dependency}
tokio = {{ version = "1", features = ["macros", "net", "rt-multi-thread"] }}
"#
        ),
    )?;
    write(
        &src.join("main.rs"),
        r#"use axum::{Router, routing::get};

#[tokio::main]
async fn main() {
    let app = Router::new().route("/", get(|| async { "hello from nidus" }));
    let listener = tokio::net::TcpListener::bind("127.0.0.1:3000").await.unwrap();
    axum::serve(listener, app).await.unwrap();
}
"#,
    )?;
    write(
        &project.join("README.md"),
        &format!(
            r#"# {name}

Generated by `cargo nidus new`.

Run:

```bash
cargo run
```
"#
        ),
    )?;
    Ok(())
}

fn generate_artifact(kind: &str, name: &str, root: &Path) -> Result<()> {
    let directory = root.join("src").join(pluralize(kind));
    fs::create_dir_all(&directory).with_context(|| format!("creating {}", directory.display()))?;
    write(&directory.join(format!("{name}.rs")), &artifact(kind, name))
}

fn inspect_routes(root: &Path) -> Result<()> {
    let controllers = root.join("src/controllers");
    if !controllers.exists() {
        return Ok(());
    }

    for entry in
        fs::read_dir(&controllers).with_context(|| format!("reading {}", controllers.display()))?
    {
        let path = entry?.path();
        if path.extension().and_then(|extension| extension.to_str()) != Some("rs") {
            continue;
        }
        let contents =
            fs::read_to_string(&path).with_context(|| format!("reading {}", path.display()))?;
        let Some(prefix) = extract_attr_value(&contents, "controller") else {
            continue;
        };
        for method in ["get", "post", "put", "patch", "delete"] {
            for route in extract_all_attr_values(&contents, method) {
                println!("{} {}", method.to_uppercase(), join_route(&prefix, &route));
            }
        }
    }
    Ok(())
}

fn inspect_graph(root: &Path) -> Result<()> {
    let modules = root.join("src/modules");
    if !modules.exists() {
        return Ok(());
    }

    for entry in fs::read_dir(&modules).with_context(|| format!("reading {}", modules.display()))? {
        let path = entry?.path();
        if path.extension().and_then(|extension| extension.to_str()) != Some("rs") {
            continue;
        }
        let contents =
            fs::read_to_string(&path).with_context(|| format!("reading {}", path.display()))?;
        for module in extract_struct_names(&contents) {
            println!("{module}");
        }
    }
    Ok(())
}

fn check_project(root: &Path) -> Result<()> {
    let required = ["Cargo.toml", "src/main.rs"];
    let missing = required
        .iter()
        .filter(|path| !root.join(path).exists())
        .copied()
        .collect::<Vec<_>>();

    if !missing.is_empty() {
        bail!(
            "Nidus project check failed for {}. Missing required files: {}",
            root.display(),
            missing.join(", ")
        );
    }

    println!("Nidus project check passed for {}", root.display());
    Ok(())
}

fn write(path: &Path, contents: &str) -> Result<()> {
    fs::write(path, contents).with_context(|| format!("writing {}", path.display()))
}

fn pluralize(kind: &str) -> String {
    match kind {
        "module" => "modules".to_owned(),
        "controller" => "controllers".to_owned(),
        "service" => "services".to_owned(),
        "repository" => "repositories".to_owned(),
        other => format!("{other}s"),
    }
}

fn artifact(kind: &str, name: &str) -> String {
    let type_name = to_pascal_case(name);
    match kind {
        "module" => format!(
            r#"use nidus::prelude::*;

#[module]
pub struct {type_name}Module;
"#
        ),
        "controller" => format!(
            r#"use nidus::prelude::*;

#[controller("/{name}")]
pub struct {type_name}Controller;

#[routes]
impl {type_name}Controller {{
    #[get("/")]
    pub async fn index(&self) {{}}
}}
"#
        ),
        "service" => format!(
            r#"use nidus::prelude::*;

#[injectable]
pub struct {type_name}Service;
"#
        ),
        "repository" => format!(
            r#"use nidus::prelude::*;

#[injectable]
pub struct {type_name}Repository;
"#
        ),
        other => format!(
            r#"// Generated Nidus {other}: {name}
"#
        ),
    }
}

fn extract_attr_value(contents: &str, attr: &str) -> Option<String> {
    extract_all_attr_values(contents, attr).into_iter().next()
}

fn extract_all_attr_values(contents: &str, attr: &str) -> Vec<String> {
    let needle = format!("#[{attr}(\"");
    contents
        .lines()
        .filter_map(|line| {
            let start = line.find(&needle)? + needle.len();
            let rest = &line[start..];
            let end = rest.find('"')?;
            Some(rest[..end].to_owned())
        })
        .collect()
}

fn extract_struct_names(contents: &str) -> Vec<String> {
    contents
        .lines()
        .filter_map(|line| line.trim().strip_prefix("pub struct "))
        .filter_map(|rest| rest.split([';', '{', '(']).next())
        .map(str::trim)
        .filter(|name| !name.is_empty())
        .map(str::to_owned)
        .collect()
}

fn join_route(prefix: &str, route: &str) -> String {
    match (prefix, route) {
        ("/", "/") => "/".to_owned(),
        ("/", route) => route.to_owned(),
        (prefix, "/") => format!("{prefix}/"),
        (prefix, route) => format!("{prefix}{route}"),
    }
}

fn to_pascal_case(name: &str) -> String {
    name.split(['-', '_'])
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().chain(chars).collect::<String>(),
                None => String::new(),
            }
        })
        .collect()
}
