use std::{
    collections::BTreeSet,
    fs,
    path::{Path, PathBuf},
    process::Command as ProcessCommand,
};

use anyhow::{Context, Result, bail};
use clap::{Parser, Subcommand};
use serde_json::{Value, json};

#[derive(Debug, Parser)]
#[command(name = "cargo-nidus", bin_name = "cargo nidus")]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Debug, Subcommand)]
enum Command {
    /// Create a new Nidus application.
    New {
        /// Project name.
        name: String,
        /// Directory where the project folder should be created.
        #[arg(long, default_value = ".")]
        path: PathBuf,
        /// Local path to the nidus facade crate, used by tests and unreleased development builds.
        #[arg(long, hide = true)]
        nidus_path: Option<PathBuf>,
    },
    /// Generate a framework artifact.
    Generate {
        /// Artifact kind: module, controller, service, or repository.
        kind: String,
        /// Artifact name.
        name: String,
        /// Project root.
        #[arg(long, default_value = ".")]
        path: PathBuf,
    },
    /// Print route metadata.
    Routes {
        /// Project root.
        #[arg(long, default_value = ".")]
        path: PathBuf,
    },
    /// Print dependency graph metadata.
    Graph {
        /// Project root.
        #[arg(long, default_value = ".")]
        path: PathBuf,
    },
    /// Print expanded generated code guidance.
    Expand {
        /// Project root.
        #[arg(long, default_value = ".")]
        path: PathBuf,
        /// Print the cargo-expand command without running it.
        #[arg(long)]
        dry_run: bool,
    },
    /// Check project structure.
    Check {
        /// Project root.
        #[arg(long, default_value = ".")]
        path: PathBuf,
    },
    /// Generate OpenAPI output.
    Openapi {
        /// Project root.
        #[arg(long, default_value = ".")]
        path: PathBuf,
    },
}

fn main() -> Result<()> {
    let args = std::env::args().collect::<Vec<_>>();
    let args = if args.get(1).is_some_and(|arg| arg == "nidus") {
        let mut stripped = Vec::with_capacity(args.len() - 1);
        stripped.push(args[0].clone());
        stripped.extend(args.iter().skip(2).cloned());
        stripped
    } else {
        args
    };
    let cli = Cli::parse_from(args);

    match cli.command {
        Command::New {
            name,
            path,
            nidus_path,
        } => create_project(&name, &path, nidus_path.as_deref()),
        Command::Generate { kind, name, path } => generate_artifact(&kind, &name, &path),
        Command::Routes { path } => inspect_routes(&path),
        Command::Graph { path } => inspect_graph(&path),
        Command::Expand { path, dry_run } => expand_project(&path, dry_run),
        Command::Check { path } => check_project(&path),
        Command::Openapi { path } => generate_openapi(&path),
    }
}

fn create_project(name: &str, root: &Path, nidus_path: Option<&Path>) -> Result<()> {
    let project = root.join(name);
    if project.exists() {
        bail!("project already exists: {}", project.display());
    }
    let src = project.join("src");
    fs::create_dir_all(&src).with_context(|| format!("creating {}", src.display()))?;
    let nidus_dependency = nidus_path
        .map(|path| format!("{{ path = {:?} }}", path.display().to_string()))
        .unwrap_or_else(|| "\"0.1\"".to_owned());
    write(
        &project.join("Cargo.toml"),
        &format!(
            r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
nidus = {nidus_dependency}
"#
        ),
    )?;
    write(
        &src.join("main.rs"),
        r#"use axum::{Router, routing::get};
use nidus::prelude::*;

#[nidus::main]
async fn main() -> std::result::Result<(), Box<dyn std::error::Error>> {
    let app = Router::new().route("/", get(|| async { "hello from nidus" }));
    Nidus::bootstrap::<AppModule>()?
        .with_router(app)
        .listen("127.0.0.1:3000")
        .await?;
    Ok(())
}

struct AppModule;

impl Module for AppModule {
    fn definition() -> ModuleDefinition {
        ModuleBuilder::new("AppModule").build()
    }
}
"#,
    )?;
    write(
        &project.join("README.md"),
        &format!(
            r#"# {name}

Generated by `cargo nidus new`.

Run:

```bash
cargo run
```
"#
        ),
    )?;
    Ok(())
}

fn generate_artifact(kind: &str, name: &str, root: &Path) -> Result<()> {
    ensure_supported_artifact(kind)?;
    let module_name = to_snake_case(name);
    if module_name.is_empty() {
        bail!("artifact name must contain at least one ASCII letter or digit");
    }
    if !module_name.starts_with(|character: char| character.is_ascii_alphabetic()) {
        bail!("artifact name must start with an ASCII letter after normalization");
    }
    let directory_name = pluralize(kind);
    let directory = root.join("src").join(&directory_name);
    fs::create_dir_all(&directory).with_context(|| format!("creating {}", directory.display()))?;
    let path = directory.join(format!("{module_name}.rs"));
    if path.exists() {
        bail!("artifact already exists: {}", path.display());
    }
    write(&path, &artifact(kind, name, &module_name))?;
    update_module_index(&directory, &module_name)?;
    update_crate_root_module(root, &directory_name)
}

fn ensure_supported_artifact(kind: &str) -> Result<()> {
    if matches!(kind, "module" | "controller" | "service" | "repository") {
        Ok(())
    } else {
        bail!(
            "unsupported artifact kind `{kind}`. Expected one of: module, controller, service, repository"
        );
    }
}

fn inspect_routes(root: &Path) -> Result<()> {
    for route in discover_routes(root)? {
        let method = route.method.to_uppercase();
        let path = route.path;
        if let Some(summary) = route.summary {
            println!("{method} {path} - {summary}");
        } else {
            println!("{method} {path}");
        }
    }
    Ok(())
}

#[derive(Debug)]
struct DiscoveredRoute {
    method: String,
    path: String,
    summary: Option<String>,
    tags: Vec<String>,
}

fn discover_routes(root: &Path) -> Result<Vec<DiscoveredRoute>> {
    let controllers = root.join("src/controllers");
    if !controllers.exists() {
        return Ok(Vec::new());
    }

    let mut routes = Vec::new();
    for entry in
        fs::read_dir(&controllers).with_context(|| format!("reading {}", controllers.display()))?
    {
        let path = entry?.path();
        if path.extension().and_then(|extension| extension.to_str()) != Some("rs") {
            continue;
        }
        let contents =
            fs::read_to_string(&path).with_context(|| format!("reading {}", path.display()))?;
        let Some(prefix) = extract_attr_value(&contents, "controller") else {
            continue;
        };
        routes.extend(discover_controller_routes(&prefix, &contents)?);
    }
    Ok(routes)
}

fn discover_controller_routes(prefix: &str, contents: &str) -> Result<Vec<DiscoveredRoute>> {
    let mut routes = Vec::new();
    let mut pending_route = None;
    let mut pending_summary = None;
    let mut pending_tags = Vec::new();

    for line in contents.lines() {
        if let Some((method, path)) = extract_route_attr_from_line(line) {
            pending_route = Some((method, path));
        }
        if let Some(args) = extract_openapi_args_from_line(line) {
            pending_summary = extract_openapi_summary(&args);
            pending_tags = extract_openapi_tags(&args)?;
        }

        if line.contains("fn ") {
            if let Some((method, path)) = pending_route.take() {
                routes.push(DiscoveredRoute {
                    method,
                    path: join_route(prefix, &path)?,
                    summary: pending_summary.take(),
                    tags: std::mem::take(&mut pending_tags),
                });
            } else {
                pending_summary = None;
                pending_tags.clear();
            }
        }
    }

    Ok(routes)
}

fn inspect_graph(root: &Path) -> Result<()> {
    for module in discover_modules(root)? {
        println!("{}", module.name);
        if !module.imports.is_empty() {
            println!("  imports: {}", module.imports.join(", "));
        }
        if !module.providers.is_empty() {
            println!("  providers: {}", module.providers.join(", "));
        }
        if !module.controllers.is_empty() {
            println!("  controllers: {}", module.controllers.join(", "));
        }
        if !module.exports.is_empty() {
            println!("  exports: {}", module.exports.join(", "));
        }
    }
    Ok(())
}

#[derive(Debug, Default)]
struct DiscoveredModule {
    name: String,
    imports: Vec<String>,
    providers: Vec<String>,
    controllers: Vec<String>,
    exports: Vec<String>,
}

fn discover_modules(root: &Path) -> Result<Vec<DiscoveredModule>> {
    let mut sources = Vec::new();
    for root_source in ["main.rs", "lib.rs"] {
        let path = root.join("src").join(root_source);
        if path.exists() {
            sources.push(path);
        }
    }
    let modules = root.join("src/modules");
    if modules.exists() {
        for entry in
            fs::read_dir(&modules).with_context(|| format!("reading {}", modules.display()))?
        {
            let path = entry?.path();
            if path.extension().and_then(|extension| extension.to_str()) == Some("rs") {
                sources.push(path);
            }
        }
    }

    let mut discovered = Vec::new();
    for path in sources {
        let contents =
            fs::read_to_string(&path).with_context(|| format!("reading {}", path.display()))?;
        let modules = discover_modules_in_source(&contents);
        if modules.is_empty() {
            discovered.extend(extract_struct_names(&contents).into_iter().map(|name| {
                DiscoveredModule {
                    name,
                    ..DiscoveredModule::default()
                }
            }));
        } else {
            discovered.extend(modules);
        }
    }
    Ok(discovered)
}

fn discover_modules_in_source(contents: &str) -> Vec<DiscoveredModule> {
    let mut modules = Vec::new();
    let mut current = None::<DiscoveredModule>;

    for line in contents.lines() {
        if let Some(name) = extract_call_arg(line, "ModuleBuilder::new") {
            if let Some(module) = current.take() {
                modules.push(module);
            }
            current = Some(DiscoveredModule {
                name,
                ..DiscoveredModule::default()
            });
        }

        if let Some(module) = current.as_mut() {
            if let Some(import) = extract_call_arg(line, ".import") {
                module.imports.push(import);
            }
            if let Some(provider) = extract_call_arg(line, ".provider") {
                module.providers.push(provider);
            }
            if let Some(controller) = extract_call_arg(line, ".controller") {
                module.controllers.push(controller);
            }
            if let Some(export) = extract_call_arg(line, ".export") {
                module.exports.push(export);
            }
        }

        if line.contains(".build()")
            && let Some(module) = current.take()
        {
            modules.push(module);
        }
    }

    if let Some(module) = current {
        modules.push(module);
    }
    modules.extend(discover_module_macro_metadata(contents));
    modules
}

fn discover_module_macro_metadata(contents: &str) -> Vec<DiscoveredModule> {
    let mut modules = Vec::new();
    let mut pending_module_attr = false;
    let mut current = None::<DiscoveredModule>;

    for line in contents.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("#[module") {
            pending_module_attr = true;
            continue;
        }

        if pending_module_attr && let Some(name) = extract_module_struct_name(trimmed) {
            let has_body = trimmed.contains('{');
            let is_unit = trimmed.contains(';');
            current = Some(DiscoveredModule {
                name,
                ..DiscoveredModule::default()
            });
            pending_module_attr = false;

            if is_unit {
                if let Some(module) = current.take() {
                    modules.push(module);
                }
            } else if !has_body {
                current = None;
            }
            continue;
        }

        if let Some(module) = current.as_mut() {
            if let Some(values) = extract_module_field_values(trimmed, "imports") {
                module.imports.extend(values);
            }
            if let Some(values) = extract_module_field_values(trimmed, "providers") {
                module.providers.extend(values);
            }
            if let Some(values) = extract_module_field_values(trimmed, "controllers") {
                module.controllers.extend(values);
            }
            if let Some(values) = extract_module_field_values(trimmed, "exports") {
                module.exports.extend(values);
            }
        }

        if trimmed.starts_with('}')
            && let Some(module) = current.take()
        {
            modules.push(module);
        }
    }

    modules
}

fn check_project(root: &Path) -> Result<()> {
    let required = ["Cargo.toml", "src/main.rs"];
    let missing = required
        .iter()
        .filter(|path| !root.join(path).exists())
        .copied()
        .collect::<Vec<_>>();

    if !missing.is_empty() {
        bail!(
            "Nidus project check failed for {}. Missing required files: {}",
            root.display(),
            missing.join(", ")
        );
    }

    validate_module_indexes(root)?;

    println!("Nidus project check passed for {}", root.display());
    Ok(())
}

fn validate_module_indexes(root: &Path) -> Result<()> {
    for directory in ["modules", "controllers", "services", "repositories"] {
        let directory = root.join("src").join(directory);
        if !directory.exists() {
            continue;
        }

        let source_modules = source_module_names(&directory)?;
        let mod_rs = directory.join("mod.rs");
        if !mod_rs.exists() {
            if let Some(module) = source_modules.first() {
                bail!(
                    "missing module index file {}: add pub mod {}; for {}",
                    mod_rs.display(),
                    module,
                    directory.join(format!("{module}.rs")).display()
                );
            }
            continue;
        }
        let contents =
            fs::read_to_string(&mod_rs).with_context(|| format!("reading {}", mod_rs.display()))?;
        let indexed_modules = contents
            .lines()
            .filter_map(extract_module_index_entry)
            .collect::<BTreeSet<_>>();

        for module in &indexed_modules {
            let expected = mod_rs
                .parent()
                .expect("mod.rs has a parent directory")
                .join(format!("{module}.rs"));
            if !expected.exists() {
                bail!(
                    "stale module index entry in {}: missing {}",
                    mod_rs.display(),
                    expected.display()
                );
            }
        }

        for module in source_modules {
            if !indexed_modules.contains(&module) {
                bail!(
                    "missing module index entry in {}: add pub mod {};",
                    mod_rs.display(),
                    module
                );
            }
        }
    }
    Ok(())
}

fn source_module_names(directory: &Path) -> Result<Vec<String>> {
    let mut modules = Vec::new();
    for entry in
        fs::read_dir(directory).with_context(|| format!("reading {}", directory.display()))?
    {
        let path = entry?.path();
        if path.file_name().and_then(|name| name.to_str()) == Some("mod.rs") {
            continue;
        }
        if path.extension().and_then(|extension| extension.to_str()) == Some("rs")
            && let Some(module) = path.file_stem().and_then(|stem| stem.to_str())
        {
            modules.push(module.to_owned());
        }
    }
    modules.sort();
    Ok(modules)
}

fn expand_project(root: &Path, dry_run: bool) -> Result<()> {
    let manifest = root.join("Cargo.toml");
    if !manifest.exists() {
        bail!(
            "Nidus expand failed for {}. Missing required file: Cargo.toml",
            root.display()
        );
    }

    if dry_run {
        println!("cargo expand --manifest-path {}", manifest.display());
        return Ok(());
    }

    let status = ProcessCommand::new("cargo")
        .arg("expand")
        .arg("--manifest-path")
        .arg(&manifest)
        .status()
        .with_context(|| "running cargo expand")?;
    if !status.success() {
        bail!("cargo expand failed for {}", root.display());
    }
    Ok(())
}

fn generate_openapi(root: &Path) -> Result<()> {
    let mut paths = serde_json::Map::new();
    for route in discover_routes(root)? {
        let entry = paths
            .entry(route.path)
            .or_insert_with(|| Value::Object(serde_json::Map::new()));
        if let Value::Object(methods) = entry {
            let mut operation = serde_json::Map::from_iter([(
                "responses".to_owned(),
                json!({
                    "200": {
                        "description": "Success"
                    }
                }),
            )]);
            if let Some(summary) = route.summary {
                operation.insert("summary".to_owned(), json!(summary));
            }
            if !route.tags.is_empty() {
                operation.insert("tags".to_owned(), json!(route.tags));
            }
            methods.insert(route.method, Value::Object(operation));
        }
    }

    println!(
        "{}",
        json!({
            "openapi": "3.1.0",
            "info": {
                "title": "Nidus API",
                "version": "0.1.0",
            },
            "paths": paths,
        })
    );
    Ok(())
}

fn write(path: &Path, contents: &str) -> Result<()> {
    fs::write(path, contents).with_context(|| format!("writing {}", path.display()))
}

fn update_module_index(directory: &Path, name: &str) -> Result<()> {
    let path = directory.join("mod.rs");
    let entry = format!("pub mod {name};");
    let mut entries = if path.exists() {
        fs::read_to_string(&path)
            .with_context(|| format!("reading {}", path.display()))?
            .lines()
            .map(str::trim)
            .filter(|line| !line.is_empty())
            .map(str::to_owned)
            .collect::<Vec<_>>()
    } else {
        Vec::new()
    };

    if !entries.iter().any(|existing| existing == &entry) {
        entries.push(entry);
        entries.sort();
    }

    let contents = if entries.is_empty() {
        String::new()
    } else {
        format!("{}\n", entries.join("\n"))
    };
    write(&path, &contents)
}

fn update_crate_root_module(root: &Path, module: &str) -> Result<()> {
    let src = root.join("src");
    let (path, visibility) = if src.join("lib.rs").exists() {
        (src.join("lib.rs"), "pub ")
    } else if src.join("main.rs").exists() {
        (src.join("main.rs"), "")
    } else {
        return Ok(());
    };
    let contents =
        fs::read_to_string(&path).with_context(|| format!("reading {}", path.display()))?;
    let private_entry = format!("mod {module};");
    let public_entry = format!("pub mod {module};");
    if contents
        .lines()
        .map(str::trim)
        .any(|line| line == private_entry || line == public_entry)
    {
        return Ok(());
    }

    let mut updated = contents;
    if !updated.ends_with('\n') {
        updated.push('\n');
    }
    updated.push_str(&format!("{visibility}mod {module};\n"));
    write(&path, &updated)
}

fn pluralize(kind: &str) -> String {
    match kind {
        "module" => "modules".to_owned(),
        "controller" => "controllers".to_owned(),
        "service" => "services".to_owned(),
        "repository" => "repositories".to_owned(),
        other => format!("{other}s"),
    }
}

fn artifact(kind: &str, name: &str, module_name: &str) -> String {
    let type_name = to_pascal_case(module_name);
    match kind {
        "module" => format!(
            r#"use nidus::prelude::*;

#[module]
#[allow(dead_code)]
pub struct {type_name}Module;
"#
        ),
        "controller" => format!(
            r#"use nidus::prelude::*;

#[controller("/{name}")]
#[allow(dead_code)]
pub struct {type_name}Controller;

#[routes]
#[allow(dead_code)]
impl {type_name}Controller {{
    #[get("/")]
    pub async fn index(&self) {{}}
}}
"#
        ),
        "service" => format!(
            r#"use nidus::prelude::*;

#[injectable]
#[allow(dead_code)]
pub struct {type_name}Service;
"#
        ),
        "repository" => format!(
            r#"use nidus::prelude::*;

#[injectable]
#[allow(dead_code)]
pub struct {type_name}Repository;
"#
        ),
        _ => unreachable!("artifact kind should be validated before rendering"),
    }
}

fn extract_attr_value(contents: &str, attr: &str) -> Option<String> {
    extract_all_attr_values(contents, attr).into_iter().next()
}

fn extract_all_attr_values(contents: &str, attr: &str) -> Vec<String> {
    contents
        .lines()
        .filter_map(|line| extract_attr_value_from_line(line, attr))
        .collect()
}

fn extract_attr_value_from_line(line: &str, attr: &str) -> Option<String> {
    let needle = format!("#[{attr}(\"");
    let start = line.find(&needle)? + needle.len();
    let rest = &line[start..];
    let end = rest.find('"')?;
    Some(rest[..end].to_owned())
}

fn extract_route_attr_from_line(line: &str) -> Option<(String, String)> {
    for method in ["get", "post", "put", "patch", "delete"] {
        if let Some(path) = extract_attr_value_from_line(line, method) {
            return Some((method.to_owned(), path));
        }
    }
    None
}

fn extract_openapi_args_from_line(line: &str) -> Option<String> {
    let needle = "#[openapi(";
    let start = line.find(needle)? + needle.len();
    let rest = &line[start..];
    let end = rest.rfind(")]")?;
    Some(rest[..end].to_owned())
}

fn extract_openapi_summary(args: &str) -> Option<String> {
    let needle = "summary = \"";
    let start = args.find(needle)? + needle.len();
    let rest = &args[start..];
    let end = rest.find('"')?;
    Some(rest[..end].to_owned())
}

fn extract_openapi_tags(args: &str) -> Result<Vec<String>> {
    let Some(tags_start) = args.find("tags") else {
        return Ok(Vec::new());
    };
    let rest = &args[tags_start..];
    let Some(open) = rest.find('[') else {
        bail!("#[openapi] tags must be an array of string literals");
    };
    let rest = &rest[open + 1..];
    let Some(close) = rest.find(']') else {
        bail!("#[openapi] tags must be an array of string literals");
    };
    let tags = &rest[..close];
    let mut values = Vec::new();
    for raw in tags.split(',') {
        let raw = raw.trim();
        if raw.is_empty() {
            continue;
        }
        let Some(value) = raw
            .strip_prefix('"')
            .and_then(|value| value.strip_suffix('"'))
        else {
            bail!("#[openapi] tags must be string literals");
        };
        values.push(value.to_owned());
    }
    Ok(values)
}

fn extract_module_index_entry(line: &str) -> Option<String> {
    let line = line.trim();
    let module = line.strip_prefix("pub mod ")?;
    let module = module.strip_suffix(';')?;
    let module = module.trim();
    if module.is_empty() {
        None
    } else {
        Some(module.to_owned())
    }
}

fn extract_call_arg(line: &str, call: &str) -> Option<String> {
    let start = line.find(call)? + call.len();
    let rest = line[start..].trim_start();
    let rest = rest.strip_prefix("(\"")?;
    let end = rest.find('"')?;
    Some(rest[..end].to_owned())
}

fn extract_struct_names(contents: &str) -> Vec<String> {
    contents
        .lines()
        .filter_map(|line| line.trim().strip_prefix("pub struct "))
        .filter_map(|rest| rest.split([';', '{', '(']).next())
        .map(str::trim)
        .filter(|name| !name.is_empty())
        .map(str::to_owned)
        .collect()
}

fn extract_module_struct_name(line: &str) -> Option<String> {
    let start = line.find("struct ")? + "struct ".len();
    let rest = line[start..].trim_start();
    let name = rest
        .split([' ', '{', ';', '(', '<'])
        .next()
        .map(str::trim)
        .filter(|name| !name.is_empty())?;
    Some(name.to_owned())
}

fn extract_module_field_values(line: &str, field: &str) -> Option<Vec<String>> {
    let start = line.find(field)? + field.len();
    let rest = line[start..].trim_start().strip_prefix(':')?.trim_start();
    let (open, close) = match rest.chars().next()? {
        '(' => ('(', ')'),
        '[' => ('[', ']'),
        _ => return None,
    };
    let values = rest.strip_prefix(open)?;
    let end = values.find(close)?;
    let values = &values[..end];
    Some(
        values
            .split(',')
            .map(str::trim)
            .filter(|value| !value.is_empty())
            .map(path_last_segment)
            .collect(),
    )
}

fn path_last_segment(path: &str) -> String {
    path.split("::")
        .last()
        .map(str::trim)
        .unwrap_or(path)
        .to_owned()
}

fn join_route(prefix: &str, route: &str) -> Result<String> {
    let prefix = normalize_path(prefix)?;
    let route = normalize_path(route)?;
    let joined = if prefix == "/" {
        route
    } else if route == "/" {
        format!("{prefix}/")
    } else {
        format!("{prefix}{route}")
    };
    Ok(convert_nest_params(&joined))
}

fn normalize_path(path: &str) -> Result<String> {
    let path = path.trim();
    validate_path(path)?;
    let normalized = if path.starts_with('/') {
        path.to_owned()
    } else {
        format!("/{path}")
    };
    Ok(normalized)
}

fn validate_path(path: &str) -> Result<()> {
    for segment in path.split('/') {
        if segment == ":" {
            bail!("route path `{path}` contains a parameter segment without a name after ':'");
        }
    }
    Ok(())
}

fn convert_nest_params(path: &str) -> String {
    path.split('/')
        .map(|segment| {
            if let Some(name) = segment.strip_prefix(':') {
                format!("{{{name}}}")
            } else {
                segment.to_owned()
            }
        })
        .collect::<Vec<_>>()
        .join("/")
}

fn to_pascal_case(name: &str) -> String {
    name.split(['-', '_'])
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().chain(chars).collect::<String>(),
                None => String::new(),
            }
        })
        .collect()
}

fn to_snake_case(name: &str) -> String {
    let mut output = String::new();
    let mut previous_was_separator = true;

    for character in name.chars() {
        if character.is_ascii_alphanumeric() {
            if character.is_ascii_uppercase() && !previous_was_separator {
                output.push('_');
            }
            output.push(character.to_ascii_lowercase());
            previous_was_separator = false;
        } else if !previous_was_separator {
            output.push('_');
            previous_was_separator = true;
        }
    }

    if output.ends_with('_') {
        output.pop();
    }
    output
}
